import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {account,rpc} from './local-api.mjs';
const founder = await account('mct57-founder'), staff = await account('mct57-staff'), director = await account('mct57-director'), outsider = await account('mct57-outsider');
const org = await rpc(founder.client,'criar_organizacao',{p_nome:'Synthetic MCT57'});
const membership = await founder.client.from('memberships').select('organization_id').eq('user_id',founder.user.id).single();
assert.ifError(membership.error);
const p_org = membership.data.organization_id;
const created = await rpc(founder.client,'event_create',{p_org,p_document:{id:randomUUID(),name:'Synthetic invited event',status:'planejamento',modules:{},participants:[],tasks:[],schedule:[]}});
const other = await rpc(founder.client,'event_create',{p_org,p_document:{id:randomUUID(),name:'Synthetic private event'}});
assert.equal(created.role,'founder'); assert.match(created.code,/^[A-F0-9]{8}$/); assert.notEqual(created.code,other.code);
const invite = await rpc(founder.client,'event_invite',{p_event:created.document.id,p_role:'director'});
const settings = await readFile('src/components/EventInvites.jsx','utf8');
assert.ok(settings.includes('Copiar código') && settings.includes('Gerar e copiar link de convite'));
assert.ok(settings.includes('/entrar?') && settings.includes('codigo: code, convite: invitation'));
console.log('CA1 PASS: API creates unique eight-character code; Settings offers code copy, role selector, generate/copy invite URL /entrar?codigo=...&convite=... .');
const joined = await rpc(staff.client,'event_join',{p_code:created.code.toLowerCase(),p_invitation:null});
assert.equal(joined.role,'staff');
const directed = await rpc(director.client,'event_join',{p_code:created.code,p_invitation:invite});
assert.equal(directed.role,'director');
for (const person of [staff,director]) {
 const events = await rpc(person.client,'event_list'); assert.equal(events.length,1); assert.equal(events[0].document.id,created.document.id);
 const orgs = await person.client.from('memberships').select('id'); assert.ifError(orgs.error); assert.deepEqual(orgs.data,[]);
}
assert.equal((await rpc(founder.client,'event_join',{p_code:created.code,p_invitation:null})).role,'founder');
console.log('CA2 PASS: code-only JWT joins as staff; director-link JWT joins as director; each sees only invited event, has zero organization memberships; creator remains founder after code entry.');
await rpc(founder.client,'event_revoke_invite',{p_invitation:invite});
let denied = await outsider.request('rpc/event_join','POST',{p_code:created.code,p_invitation:invite});
assert.equal(denied.status,400); assert.match(denied.body.message,/revogado/);
console.log(`CA3 revoked-link: HTTP ${denied.status}, message=${denied.body.message}`);
await rpc(founder.client,'event_code_enabled',{p_event:created.document.id,p_enabled:false});
denied = await outsider.request('rpc/event_join','POST',{p_code:created.code,p_invitation:null});
assert.equal(denied.status,400); assert.match(denied.body.message,/revogado/);
console.log(`CA3 revoked-code: HTTP ${denied.status}, message=${denied.body.message}`);
denied = await outsider.request('rpc/event_join','POST',{p_code:'INVALID!',p_invitation:null});
assert.equal(denied.status,400); assert.match(denied.body.message,/inválido/);
assert.deepEqual(await rpc(outsider.client,'event_list'),[]);
console.log(`CA3 invalid-code: HTTP ${denied.status}, message=${denied.body.message}; outsider still has zero events.`);
const log = await founder.client.from('event_join_log').select('user_id,joined_at,invitation_id,role,entry_kind').eq('event_id',created.document.id);
assert.ifError(log.error);
assert.ok(log.data.some(e=>e.user_id===director.user.id && e.invitation_id===invite && e.role==='director' && e.entry_kind==='link' && Date.parse(e.joined_at)));
assert.ok(log.data.some(e=>e.user_id===staff.user.id && e.invitation_id===null && e.role==='staff' && e.entry_kind==='code' && Date.parse(e.joined_at)));
console.log('CA4 PASS: authenticated database read contains user_id, joined_at, invitation_id, role and entry_kind for both entries.');
denied = await staff.request('rpc/event_invite','POST',{p_event:created.document.id,p_role:'director'});
assert.equal(denied.status,403); assert.equal(denied.body.code,'42501');
console.log(`RLS restricted-JWT invite escalation: HTTP ${denied.status}, SQLSTATE ${denied.body.code}, message=${denied.body.message}`);
denied = await outsider.request(`platform_events?id=eq.${created.document.id}&select=id`);
assert.equal(denied.status,200); assert.deepEqual(denied.body,[]);
console.log('RLS outsider direct table GET: HTTP 200 [] (zero authorized rows).');
console.log('Local synthetic fixtures retained; no remote project accessed and no data deleted.');
