import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import React from 'react';
import {act,create} from 'react-test-renderer';
import {MemoryRouter} from 'react-router-dom';
import ts from 'typescript';
import {account,rpc,permitMultiple} from './local-api.mjs';
const user=await account('mct46-limited');
await rpc(user.client,'criar_organizacao',{p_nome:'Synthetic limited account'});
const memberships=await user.client.from('memberships').select('organization_id').eq('user_id',user.user.id);assert.ifError(memberships.error);
const org=memberships.data[0].organization_id;
const before=await rpc(user.client,'event_creation_permission');assert.deepEqual(before,{canCreate:true,eventCount:0,eventLimit:1,multiEvent:false});
const directory=await mkdtemp(resolve('node_modules/.limit-ui-'));let tree;
try {
 await writeFile(join(directory,'mocks.mjs'),`import React from 'react'; export const useEvent=()=>globalThis.__limitContext; export const EventBackupImport=()=>null; export const LogoutButton=()=>null; export const formatDateFull=()=>''; export const daysUntil=()=>0; export const cn=(...x)=>x.filter(Boolean).join(' '); export const StatusPill=()=>null; export const Button=({children,variant,size,...props})=>React.createElement('button',props,children); export const Input=props=>React.createElement('input',props); export const CityField=()=>null; export const Label=({children,...props})=>React.createElement('label',props,children);`);
 await writeFile(join(directory,'access.mjs'),await readFile('src/lib/eventAccess.js','utf8'));
 await writeFile(join(directory,'contact.mjs'),await readFile('src/lib/contact.js','utf8'));
 await writeFile(join(directory,'limit.mjs'),(await readFile('src/lib/eventLimit.js','utf8')).replace("'./contact.js'","'./contact.mjs'"));
 for(const [input,output] of [['src/pages/Events.jsx','events.mjs'],['src/pages/CreateEvent.jsx','create.mjs']]){
  let source=await readFile(input,'utf8');source=source.replaceAll("'@/lib/eventAccess'","'./access.mjs'").replaceAll("'@/lib/eventLimit'","'./limit.mjs'");
  for(const alias of ['@/components/EventBackupImport','@/components/LogoutButton','@/context/EventContext','@/lib/format','@/lib/utils','@/components/common/Primitives','@/components/ui/button','@/components/ui/input','@/components/ui/label','@/components/common/CityField'])source=source.replaceAll(`'${alias}'`,"'./mocks.mjs'");
  for(const name of ['EventBackupImport','LogoutButton','CityField'])source=source.replace(`import ${name} from './mocks.mjs'`,`import {${name}} from './mocks.mjs'`);
  await writeFile(join(directory,output),ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext}}).outputText);
 }
 const {default:Events}=await import(pathToFileURL(join(directory,'events.mjs'))),{default:CreateEvent}=await import(pathToFileURL(join(directory,'create.mjs')));
 const mount=(permission,events=[],Component=Events)=>{globalThis.__limitContext={events,eventAccess:Object.fromEntries(events.map(event=>[event.id,{role:'founder'}])),canCreateEvent:permission.canCreate,eventLimit:permission.eventLimit,updateEventById:()=>{},addEvent:()=>{throw Error('UI must not create when limited');}};act(()=>{tree=create(React.createElement(MemoryRouter,{future:{v7_startTransition:true,v7_relativeSplatPath:true}},React.createElement(Component)));});};
 const createButtons=()=>tree.root.findAllByType('button').filter(button=>button.children.some(child=>typeof child==='string' && /Criar evento|Novo evento/.test(child)));
 mount(before);assert.equal(createButtons().length,1);act(()=>tree.unmount());
 console.log('CA1 UI/API PASS: new unflagged account has eventCount=0, canCreate=true; actual Events renders Criar evento.');
 const event=await rpc(user.client,'event_create',{p_org:org,p_document:{id:randomUUID(),name:'Synthetic first event',status:'planejamento',modules:{}}});
 assert.equal(event.creationPermission.canCreate,false);
 const after=await rpc(user.client,'event_creation_permission');assert.equal(after.canCreate,false);assert.equal(after.eventCount,1);
 mount(after,[event.document]);assert.equal(createButtons().length,0);assert.ok(tree.root.findAllByType('button').some(button=>button.children.join('')==='Entrar em um evento'));act(()=>tree.unmount());
 mount(after,[event.document],CreateEvent);assert.equal(createButtons().length,0);assert.ok(tree.root.findByProps({role:'alert'}).children.join('').includes('Seu plano permite 1 evento ativo. Para criar outro, fale com a gente.'));act(()=>tree.unmount());
 console.log('CA2 UI/API PASS: existing unflagged account has canCreate=false; Events hides all create buttons; direct /novo CreateEvent shows limit alert with no creation control.');
 const metadata=await user.client.auth.updateUser({data:{multi_event:true,role:'founder'}});assert.ifError(metadata.error);
 let denied=await user.request('rpc/event_create','POST',{p_org:org,p_document:{id:randomUUID(),name:'Forbidden second event'}});assert.equal(denied.status,403);assert.equal(denied.body.code,'42501');assert.equal(denied.body.message,'Seu plano permite 1 evento ativo. Para criar outro, fale com a gente.');
 console.log(`CA3 restricted-JWT POST event_create: HTTP ${denied.status}, SQLSTATE ${denied.body.code}, message=${denied.body.message}; editable Auth metadata cannot bypass.`);
 denied=await user.request(`user_event_permissions?user_id=eq.${user.user.id}`,'PATCH',{multi_event:true});assert.equal(denied.status,403);
 console.log('RLS flag escalation: direct PATCH with account JWT returns HTTP 403.');
 await permitMultiple(user);const released=await rpc(user.client,'event_creation_permission');assert.equal(released.multiEvent,true);assert.equal(released.canCreate,true);
 await rpc(user.client,'event_create',{p_org:org,p_document:{id:randomUUID(),name:'Synthetic administratively released second'}});
 console.log('FLAG PASS: trusted local admin flag update permits second event without frontend deploy.');
 const founder=await account('mct46-platform-founder','renannascimento0304@gmail.com');
 await rpc(founder.client,'criar_organizacao',{p_nome:'Synthetic platform founder'});
 const orgs=await founder.client.from('memberships').select('organization_id').eq('user_id',founder.user.id);assert.ifError(orgs.error);
 const exception=await rpc(founder.client,'event_creation_permission');assert.equal(exception.multiEvent,true);
 for(let i=0;i<2;i++)await rpc(founder.client,'event_create',{p_org:orgs.data[0].organization_id,p_document:{id:randomUUID(),name:`Synthetic founder event ${i}`}});
 console.log('CA4 API PASS: specified founder email is seeded multiEvent=true automatically; first and second event creation both succeed.');
 const parallel=await account('mct46-concurrent');
 for(let i=0;i<2;i++)await rpc(parallel.client,'criar_organizacao',{p_nome:`Synthetic concurrent org ${i}`});
 const targets=await parallel.client.from('memberships').select('organization_id').eq('user_id',parallel.user.id);assert.ifError(targets.error);
 const attempts=await Promise.all(targets.data.map(target=>parallel.client.rpc('event_create',{p_org:target.organization_id,p_document:{id:randomUUID(),name:'Synthetic racing event'}})));
 assert.equal(attempts.filter(result=>!result.error).length,1);assert.equal(attempts.filter(result=>result.error?.code==='42501').length,1);
 assert.equal((await rpc(parallel.client,'event_creation_permission')).eventCount,1);
 console.log('CONCURRENCY PASS: two simultaneous creations in different organizations yield exactly one success and one SQLSTATE 42501; account count remains one.');
 console.log('Synthetic local users/events retained; no remote flag updates, deletions or production deployment.');
} finally {if(tree)act(()=>tree.unmount());delete globalThis.__limitContext;await rm(directory,{recursive:true,force:true});}
